package com.slideindex.app.ui

enum class SettingsDestination {
    Main,
    NotificationHub,
    AppKeepAlive,
    Layout,
    HiddenApps,
    ExcludedApps,
    FreeWindow,
    FreeWindowPreview,
    TriggerCollection,
    SideGesturesAppearance,
    SideGesturesDesign,
    SideGesturesLeft,
    SideGesturesRight,
    QuickLauncher,
    ShellCommands,
    WidgetPanel,
    NotificationHistory,
    OtpHub,
    OtpSettings,
    OtpRecords,
    OtpRulesList,
    OtpAutoInput,
    FloatingPointer,
    FloatingPointerPointer,
    FloatingPointerJoystick,
    GestureAngle,
    AnimationStyleSelect,
    WaveAnimationStyle,
    CapsuleAnimationStyle,
    BubbleAnimationStyle,
}
