package defpackage;

import android.os.Build;
import android.util.DisplayMetrics;
import com.quickcursor.App;
import com.quickcursor.R;
import java.util.HashSet;

/* JADX INFO: compiled from: r8-map-id-cf80f8abcb113d5feb50392a150ad1aafcd9a0d68b58b47d245bdd7749062c30 */
/* JADX INFO: loaded from: classes.dex */
public abstract class dn {
    public static final int A0;
    public static final int A1;
    public static final String A2;
    public static final int B0;
    public static final int B1;
    public static final String B2;
    public static final int C0;
    public static final int C1;
    public static final String C2;
    public static final float D0;
    public static final int D1;
    public static final String D2;
    public static final float E0;
    public static final String E1;
    public static final boolean E2;
    public static final boolean F;
    public static final float F0;
    public static final HashSet F1;
    public static final String F2;
    public static final boolean G;
    public static final int G0;
    public static final boolean G1;
    public static final int G2;
    public static final boolean H;
    public static final float H0;
    public static final String H1;
    public static final boolean H2;
    public static final boolean I;
    public static final float I0;
    public static final String I1;
    public static final int I2;
    public static final boolean J;
    public static final int J0;
    public static final int J1;
    public static final boolean J2;
    public static final int K;
    public static final int K0;
    public static final String K1;
    public static final boolean K2;
    public static final int L;
    public static final int L0;
    public static final String L1;
    public static final boolean L2;
    public static final int M;
    public static final int M0;
    public static final int M1;
    public static final boolean M2;
    public static final float N;
    public static final int N0;
    public static final String N1;
    public static final int N2;
    public static final int O;
    public static final int O0;
    public static final int O1;
    public static final int O2;
    public static final String P;
    public static final int P0;
    public static final boolean P1;
    public static final int P2;
    public static final float Q;
    public static final int Q0;
    public static final boolean Q1;
    public static final boolean Q2;
    public static final int R;
    public static final int R0;
    public static final boolean R1;
    public static final boolean R2;
    public static final String S;
    public static final int S0;
    public static final boolean S1;
    public static final boolean S2;
    public static final String T;
    public static final int T0;
    public static final String T1;
    public static final String U;
    public static final int U0;
    public static final Boolean U1;
    public static final String V;
    public static final int V0;
    public static final Boolean V1;
    public static final String W;
    public static final boolean W0;
    public static final Boolean W1;
    public static final String X;
    public static final boolean X0;
    public static final Integer X1;
    public static final String Y;
    public static final boolean Y0;
    public static final Integer Y1;
    public static final int Z;
    public static final float Z0;
    public static final Integer Z1;
    public static final int a0;
    public static final String a1;
    public static final Integer a2;
    public static final int b0;
    public static final int b1;
    public static final Integer b2;
    public static final int c0;
    public static final boolean c1;
    public static final Boolean c2;
    public static final int d0;
    public static final String d1;
    public static final String d2;
    public static final int e0;
    public static final int e1;
    public static final String e2;
    public static final int f0;
    public static final int f1;
    public static final String f2;
    public static final int g0;
    public static final int g1;
    public static final Integer g2;
    public static final int h0;
    public static final float h1;
    public static final Integer h2;
    public static final int i0;
    public static final int i1;
    public static final Boolean i2;
    public static final int j0;
    public static final int j1;
    public static final String j2;
    public static final int k0;
    public static final int k1;
    public static final String k2;
    public static final int l0;
    public static final int l1;
    public static final int l2;
    public static final int m0;
    public static final int m1;
    public static final int m2;
    public static final int n0;
    public static final int n1;
    public static final String n2;
    public static final int o0;
    public static final int o1;
    public static final String o2;
    public static final int p0;
    public static final int p1;
    public static final String p2;
    public static final int q0;
    public static final float q1;
    public static final Integer q2;
    public static final int r0;
    public static final int r1;
    public static final boolean r2;
    public static final float s0;
    public static final int s1;
    public static final boolean s2;
    public static final float t0;
    public static final int t1;
    public static final boolean t2;
    public static final float u0;
    public static final int u1;
    public static final boolean u2;
    public static final boolean v0;
    public static final int v1;
    public static final boolean v2;
    public static final int w0;
    public static final int w1;
    public static final boolean w2;
    public static final int x0;
    public static final int x1;
    public static final String x2;
    public static final float y0;
    public static final int y1;
    public static final String y2;
    public static final int z0;
    public static final int z1;
    public static final boolean z2;
    public static final String a = lc1.K(R.string.quick_cursor_pro);
    public static final String b = lc1.K(R.string.quick_cursor_pro_2);
    public static final String c = lc1.K(R.string.quick_cursor_pro_3);
    public static final String d = lc1.K(R.string.quick_cursor_pro_subscription);
    public static final String e = lc1.K(R.string.quick_cursor_pro_offer_free_trial_tag);
    public static final String f = lc1.K(R.string.app_share_url);
    public static final String g = lc1.K(R.string.reddit_subreddit_url);
    public static final String h = lc1.K(R.string.telegram_channel_url);
    public static final String i = lc1.K(R.string.xda_thread_url);
    public static final String j = lc1.K(R.string.translation_tool_url);
    public static final String k = lc1.K(R.string.mail_url);
    public static final String l = lc1.K(R.string.faq_url);
    public static final boolean m = lc1.w(R.bool.default_hide_on_outside_action_enabled);
    public static final boolean n = lc1.w(R.bool.default_hide_on_fling_enabled);
    public static final boolean o = lc1.w(R.bool.default_hide_timeout_enabled);
    public static final boolean p = lc1.w(R.bool.default_cursor_hide_on_tracker_release);
    public static final int q = lc1.D(R.integer.default_hide_timeout_threshold);
    public static final int r = lc1.D(R.integer.default_vibration_duration);
    public static final int s = lc1.D(R.integer.default_vibration_amplitude);
    public static final int t = lc1.D(R.integer.default_ripple_duration);
    public static final int u = lc1.D(R.integer.default_auto_tap_delay);
    public static final float v = lc1.z(R.dimen.default_click_distance_threshold);
    public static final int w = lc1.D(R.integer.default_trail_lifespan);
    public static final boolean x = lc1.w(R.bool.default_vibration_on_trigger_start);
    public static final boolean y = lc1.w(R.bool.default_vibration_on_click);
    public static final boolean z = lc1.w(R.bool.default_vibration_on_cursor_action);
    public static final boolean A = lc1.w(R.bool.default_ripple_on_click);
    public static final boolean B = lc1.w(R.bool.default_ripple_on_cursor_action);
    public static final boolean C = lc1.w(R.bool.default_dispatch_bug_popup);
    public static final boolean D = lc1.w(R.bool.default_debug_visual);
    public static final boolean E = lc1.w(R.bool.default_debug_logs);

    static {
        String str = Build.MANUFACTURER;
        F = str.equalsIgnoreCase("oneplus") ? Build.VERSION.SDK_INT >= 34 : lc1.w(R.bool.default_system_gesture_overlap);
        G = lc1.w(R.bool.default_gesture_recorder_edge_cancel);
        H = lc1.w(R.bool.default_edge_actions_visual_feedback);
        I = lc1.w(R.bool.default_edge_actions_vibration_feedback);
        J = lc1.w(R.bool.default_edge_actions_preview_icon);
        K = lc1.D(R.integer.default_edge_actions_preview_sensitivity);
        L = lc1.D(R.integer.default_edge_actions_preview_size);
        M = App.c.getColor(R.color.default_edge_actions_visual_color);
        N = lc1.z(R.dimen.default_edge_actions_visual_size);
        O = lc1.D(R.integer.default_edge_actions_visual_opacity);
        P = lc1.K(R.string.default_edge_actions_trigger_mode);
        Q = lc1.z(R.dimen.default_edge_actions_threshold);
        R = lc1.D(R.integer.default_edge_actions_delay);
        S = lc1.K(R.string.default_debug_logs_content);
        T = lc1.K(R.string.default_trail_type);
        U = lc1.K(R.string.default_cursor_design);
        V = lc1.K(R.string.default_tracker_design);
        W = lc1.K(R.string.default_auto_tap_mode);
        X = lc1.K(R.string.default_keyboard_triggers_handle);
        Y = lc1.K(R.string.default_keyboard_tracker_handle);
        Z = App.c.getColor(R.color.default_cursor_design1_stroke_color);
        a0 = App.c.getColor(R.color.default_cursor_design1_fill_color);
        b0 = App.c.getColor(R.color.default_cursor_design1_dot_color);
        c0 = App.c.getColor(R.color.default_trail_color);
        d0 = App.c.getColor(R.color.default_gesture_recorder_color);
        e0 = App.c.getColor(R.color.default_tracker_design_color);
        f0 = App.c.getColor(R.color.default_tracker_inside_color);
        g0 = App.c.getColor(R.color.default_tracker_outside_color);
        h0 = lc1.D(R.integer.default_tracker_opacity_percent);
        i0 = App.c.getColor(R.color.area_trigger_preview_color);
        j0 = App.c.getColor(R.color.area_tracker_preview_color);
        k0 = App.c.getColor(R.color.area_cursor_preview_color);
        l0 = App.c.getColor(R.color.debug_tracker_color);
        m0 = App.c.getColor(R.color.debug_canvas_color);
        n0 = App.c.getColor(R.color.default_ripple_click_color);
        o0 = App.c.getColor(R.color.default_ripple_cursor_action_color);
        p0 = lc1.z(R.dimen.drag_threshold);
        q0 = lc1.z(R.dimen.floating_min_snap_threshold);
        r0 = lc1.z(R.dimen.floating_max_snap_threshold);
        s0 = lc1.z(R.dimen.default_cursor_size);
        t0 = lc1.z(R.dimen.default_cursor_design1_stroke_size);
        u0 = lc1.z(R.dimen.default_cursor_tip_size);
        v0 = lc1.w(R.bool.default_cursor_mirrored);
        w0 = lc1.z(R.dimen.default_keyboard_above_extra);
        x0 = lc1.D(R.integer.default_keyboard_thinner_percentage);
        y0 = lc1.z(R.dimen.default_tracker_size);
        z0 = lc1.D(R.integer.default_tracker_design_gradient_radius);
        A0 = lc1.D(R.integer.default_tracker_design_squircle_radius);
        B0 = lc1.D(R.integer.default_tracker_design_rounded_rectangle_radius);
        C0 = (int) (((double) ey0.d) * 0.7d);
        D0 = lc1.z(R.dimen.default_tracker_actions_inside_size);
        E0 = lc1.z(R.dimen.default_tracker_actions_outside_size);
        F0 = lc1.z(R.dimen.default_tracker_actions_stroke_size);
        G0 = lc1.D(R.integer.default_tracker_actions_icon_size);
        H0 = lc1.z(R.dimen.default_trigger_actions_pie_stroke_size);
        I0 = lc1.z(R.dimen.default_trigger_actions_pie_icon_size);
        J0 = App.c.getColor(R.color.default_tracker_actions_inside_color);
        K0 = App.c.getColor(R.color.default_tracker_actions_outside_color);
        L0 = App.c.getColor(R.color.default_tracker_actions_stroke_color);
        M0 = App.c.getColor(R.color.default_tracker_actions_icon_color);
        N0 = App.c.getColor(R.color.default_trigger_actions_pie_color);
        O0 = App.c.getColor(R.color.default_trigger_actions_pie_selected_color);
        P0 = App.c.getColor(R.color.default_trigger_actions_pie_stroke_color);
        Q0 = App.c.getColor(R.color.default_trigger_actions_pie_icon_color);
        R0 = lc1.z(R.dimen.default_trigger_actions_action_icon_icon_offset_x);
        S0 = lc1.z(R.dimen.default_trigger_actions_action_icon_icon_offset_y);
        T0 = lc1.z(R.dimen.default_trigger_actions_action_icon_icon_size);
        U0 = App.c.getColor(R.color.default_trigger_actions_action_icon_icon_color);
        V0 = App.c.getColor(R.color.default_trigger_actions_action_icon_background_color);
        W0 = lc1.w(R.bool.default_tracker_actions_always_visible);
        X0 = lc1.w(R.bool.default_tracker_actions_auto_sweep_offset);
        Y0 = lc1.w(R.bool.default_tracker_actions_vibration_feedback);
        Z0 = lc1.D(R.integer.default_tracker_actions_sweep_offset) * 1.0f;
        a1 = lc1.K(R.string.default_tracker_actions_trigger_mode);
        b1 = lc1.D(R.integer.default_tracker_actions_trigger_delay);
        c1 = lc1.w(R.bool.default_tracker_actions_center_action_icon);
        d1 = lc1.K(R.string.default_tracker_actions_center_action_trigger_mode);
        e1 = lc1.z(R.dimen.default_floating_edge_tracker_size);
        f1 = ey0.d / 2;
        g1 = lc1.D(R.integer.default_floating_edge_tracker_opacity_percent);
        h1 = lc1.z(R.dimen.default_ripple_size);
        i1 = lc1.z(R.dimen.trail_drawable_low_min_distance);
        j1 = lc1.z(R.dimen.trail_drawable_low_max_distance);
        k1 = lc1.z(R.dimen.trail_drawable_high_min_distance);
        l1 = lc1.z(R.dimen.trail_drawable_high_max_distance);
        m1 = lc1.D(R.integer.trail_drawable_low_min_time);
        n1 = lc1.D(R.integer.trail_drawable_low_max_time);
        o1 = lc1.D(R.integer.trail_drawable_high_min_time);
        p1 = lc1.D(R.integer.trail_drawable_high_max_time);
        q1 = lc1.z(R.dimen.default_simple_trigger_size);
        r1 = lc1.z(R.dimen.max_simple_trigger_size);
        s1 = lc1.D(R.integer.default_portrait_simple_trigger_position);
        t1 = lc1.D(R.integer.default_portrait_simple_trigger_length);
        u1 = lc1.D(R.integer.default_portrait_simple_cursor_speed);
        v1 = lc1.D(R.integer.default_portrait_simple_cursor_area_size);
        w1 = lc1.D(R.integer.default_portrait_simple_tracker_align);
        x1 = lc1.D(R.integer.default_portrait_simple_tracker_distance);
        y1 = lc1.D(R.integer.default_landscape_simple_trigger_position);
        z1 = lc1.D(R.integer.default_landscape_simple_cursor_speed);
        A1 = lc1.D(R.integer.default_landscape_simple_cursor_area_size);
        B1 = lc1.D(R.integer.default_landscape_simple_tracker_align);
        C1 = lc1.D(R.integer.default_landscape_simple_tracker_distance);
        D1 = lc1.z(R.dimen.default_trigger_side_width);
        DisplayMetrics displayMetrics = ey0.a;
        E1 = lc1.K(R.string.default_app_filter_mode);
        F1 = new HashSet();
        G1 = lc1.w(R.bool.default_limited_mode);
        H1 = lc1.K(R.string.default_free_long_tap_tracker_action);
        I1 = lc1.K(R.string.default_pro_long_tap_tracker_action);
        J1 = lc1.D(R.integer.default_long_tap_tracker_time_threshold);
        K1 = lc1.K(R.string.default_double_tap_tracker_action_type);
        L1 = lc1.K(R.string.default_double_tap_tracker_action);
        M1 = lc1.D(R.integer.default_double_tap_tracker_time_threshold);
        lc1.K(R.string.default_second_tap_tracker_action_type);
        N1 = lc1.K(R.string.default_second_tap_tracker_action);
        O1 = lc1.z(R.dimen.second_tap_tracker_action_threshold);
        P1 = (!str.equalsIgnoreCase("google") || Build.VERSION.SDK_INT < 32) ? lc1.w(R.bool.default_material_you_coloring) : lc1.w(R.bool.default_material_you_coloring_google_api_32);
        Q1 = lc1.w(R.bool.default_disabled_while_spen_detached);
        R1 = lc1.w(R.bool.default_enabled_on_lockscreen);
        S1 = lc1.w(R.bool.default_app_stopped);
        T1 = lc1.K(R.string.default_action_volume_bar_mode);
        U1 = Boolean.valueOf(lc1.w(R.bool.default_action_volume_show_ui));
        V1 = Boolean.valueOf(lc1.w(R.bool.default_action_expand_notification_toggle));
        W1 = Boolean.valueOf(lc1.w(R.bool.default_action_launch_assistant_hide_cursor));
        X1 = Integer.valueOf(lc1.D(R.integer.default_action_volume_bar_granularity));
        Y1 = Integer.valueOf(lc1.D(R.integer.default_action_bar_max_update_percentage));
        Z1 = Integer.valueOf(lc1.D(R.integer.default_action_bar_swipe_max_update_percentage));
        a2 = Integer.valueOf(lc1.D(R.integer.default_action_bar_smooth_time));
        b2 = Integer.valueOf(lc1.D(R.integer.default_action_bar_swipe_smooth_time));
        c2 = Boolean.valueOf(lc1.w(R.bool.default_action_bar_hide_cursor));
        d2 = lc1.K(R.string.default_action_bar_orientation);
        e2 = lc1.K(R.string.default_action_bar_swipe_orientation);
        f2 = lc1.K(R.string.default_action_bar_mode);
        g2 = Integer.valueOf(lc1.D(R.integer.default_action_bar_vertical_position));
        h2 = Integer.valueOf(lc1.D(R.integer.default_action_timed_disable_seconds));
        String lowerCase = str.toLowerCase();
        String lowerCase2 = Build.BRAND.toLowerCase();
        i2 = Boolean.valueOf((lowerCase.contains("oneplus") || lowerCase.contains("oppo") || lowerCase.contains("realme") || lowerCase2.contains("oneplus") || lowerCase2.contains("oppo") || lowerCase2.contains("realme")) ? lc1.w(R.bool.default_action_volume_bar_accessibility_stream_oppo) : lc1.w(R.bool.default_action_volume_bar_accessibility_stream));
        j2 = lc1.K(R.string.default_action_gesture_swipe_direction);
        k2 = lc1.K(R.string.default_action_gesture_swipe_distance);
        l2 = lc1.D(R.integer.default_action_gesture_swipe_duration);
        m2 = lc1.D(R.integer.default_action_long_tap_duration);
        n2 = lc1.K(R.string.default_action_gesture_pinch_distance);
        o2 = lc1.K(R.string.default_action_gesture_pinch_duration);
        p2 = lc1.K(R.string.default_action_brightness_bar_mode);
        q2 = Integer.valueOf(lc1.D(R.integer.default_action_volume_steps));
        r2 = lc1.w(R.bool.default_action_screenshot_clipboard_copy);
        s2 = lc1.w(R.bool.default_action_screenshot_clipboard_save_file);
        t2 = lc1.w(R.bool.default_action_screenshot_clipboard_after_crop);
        u2 = lc1.w(R.bool.default_action_screenshot_clipboard_after_share);
        v2 = lc1.w(R.bool.default_action_screenshot_clipboard_after_save);
        w2 = lc1.w(R.bool.default_action_screenshot_clipboard_after_delete);
        x2 = lc1.K(R.string.default_action_screenshot_clipboard_execute_after);
        y2 = lc1.K(R.string.default_extra_rotation_mode);
        z2 = lc1.w(R.bool.default_action_launch_app_windowed_mode);
        A2 = lc1.K(R.string.default_windowed_launch_mode);
        B2 = lc1.K(R.string.default_icon_pack_name);
        C2 = lc1.K(R.string.default_simple_trigger_sides);
        D2 = lc1.K(R.string.default_trigger_design_type);
        E2 = lc1.w(R.bool.default_trigger_actions_vibration_feedback);
        F2 = lc1.K(R.string.default_trigger_actions_trigger_mode);
        G2 = lc1.D(R.integer.default_trigger_actions_trigger_delay);
        H2 = lc1.w(R.bool.default_trigger_actions_pie_animation);
        I2 = lc1.D(R.integer.default_trigger_actions_pie_animation_duration);
        J2 = lc1.w(R.bool.default_action_bar_show_bar);
        K2 = lc1.w(R.bool.default_action_volume_swipe_show_bar);
        L2 = lc1.w(R.bool.default_action_volume_bar_show_bar);
        M2 = lc1.w(R.bool.default_action_brightness_show_bar);
        N2 = lc1.D(R.integer.default_action_bar_swipe_swipe_length);
        O2 = App.c.getColor(R.color.default_trigger_design_background_color);
        P2 = App.c.getColor(R.color.default_trigger_design_glow_color);
        Q2 = lc1.w(R.bool.default_input_dispatcher_bug_on_detected);
        R2 = lc1.w(R.bool.default_input_dispatcher_bug_on_tracker_release);
        S2 = lc1.w(R.bool.default_input_dispatcher_bug_on_tracker_long_tap);
    }
}
