package defpackage;

import android.view.ViewGroup;
import java.util.Arrays;
import java.util.HashMap;

/* JADX INFO: compiled from: r8-map-id-cf80f8abcb113d5feb50392a150ad1aafcd9a0d68b58b47d245bdd7749062c30 */
/* JADX INFO: loaded from: classes.dex */
public final class pn {
    public int a;
    public final sn b;
    public final rn c;
    public final qn d;
    public final tn e;
    public HashMap f;

    public pn() {
        sn snVar = new sn();
        snVar.a = 0;
        snVar.b = 0;
        snVar.c = 1.0f;
        snVar.d = Float.NaN;
        this.b = snVar;
        rn rnVar = new rn();
        rnVar.a = -1;
        rnVar.b = 0;
        rnVar.c = -1;
        rnVar.d = Float.NaN;
        rnVar.e = Float.NaN;
        rnVar.f = Float.NaN;
        rnVar.g = -1;
        rnVar.h = null;
        rnVar.i = -1;
        this.c = rnVar;
        qn qnVar = new qn();
        qnVar.a = false;
        qnVar.d = -1;
        qnVar.e = -1;
        qnVar.f = -1.0f;
        qnVar.g = true;
        qnVar.h = -1;
        qnVar.i = -1;
        qnVar.j = -1;
        qnVar.k = -1;
        qnVar.l = -1;
        qnVar.m = -1;
        qnVar.n = -1;
        qnVar.o = -1;
        qnVar.p = -1;
        qnVar.q = -1;
        qnVar.r = -1;
        qnVar.s = -1;
        qnVar.t = -1;
        qnVar.u = -1;
        qnVar.v = -1;
        qnVar.w = 0.5f;
        qnVar.x = 0.5f;
        qnVar.y = null;
        qnVar.z = -1;
        qnVar.A = 0;
        qnVar.B = 0.0f;
        qnVar.C = -1;
        qnVar.D = -1;
        qnVar.E = -1;
        qnVar.F = 0;
        qnVar.G = 0;
        qnVar.H = 0;
        qnVar.I = 0;
        qnVar.J = 0;
        qnVar.K = 0;
        qnVar.L = 0;
        qnVar.M = Integer.MIN_VALUE;
        qnVar.N = Integer.MIN_VALUE;
        qnVar.O = Integer.MIN_VALUE;
        qnVar.P = Integer.MIN_VALUE;
        qnVar.Q = Integer.MIN_VALUE;
        qnVar.R = Integer.MIN_VALUE;
        qnVar.S = Integer.MIN_VALUE;
        qnVar.T = -1.0f;
        qnVar.U = -1.0f;
        qnVar.V = 0;
        qnVar.W = 0;
        qnVar.X = 0;
        qnVar.Y = 0;
        qnVar.Z = 0;
        qnVar.a0 = 0;
        qnVar.b0 = 0;
        qnVar.c0 = 0;
        qnVar.d0 = 1.0f;
        qnVar.e0 = 1.0f;
        qnVar.f0 = -1;
        qnVar.g0 = 0;
        qnVar.h0 = -1;
        qnVar.l0 = false;
        qnVar.m0 = false;
        qnVar.n0 = true;
        qnVar.o0 = 0;
        this.d = qnVar;
        tn tnVar = new tn();
        tnVar.a = 0.0f;
        tnVar.b = 0.0f;
        tnVar.c = 0.0f;
        tnVar.d = 1.0f;
        tnVar.e = 1.0f;
        tnVar.f = Float.NaN;
        tnVar.g = Float.NaN;
        tnVar.h = -1;
        tnVar.i = 0.0f;
        tnVar.j = 0.0f;
        tnVar.k = 0.0f;
        tnVar.l = false;
        tnVar.m = 0.0f;
        this.e = tnVar;
        this.f = new HashMap();
    }

    public final void a(kn knVar) {
        qn qnVar = this.d;
        knVar.e = qnVar.h;
        knVar.f = qnVar.i;
        knVar.g = qnVar.j;
        knVar.h = qnVar.k;
        knVar.i = qnVar.l;
        knVar.j = qnVar.m;
        knVar.k = qnVar.n;
        knVar.l = qnVar.o;
        knVar.m = qnVar.p;
        knVar.n = qnVar.q;
        knVar.o = qnVar.r;
        knVar.s = qnVar.s;
        knVar.t = qnVar.t;
        knVar.u = qnVar.u;
        knVar.v = qnVar.v;
        ((ViewGroup.MarginLayoutParams) knVar).leftMargin = qnVar.F;
        ((ViewGroup.MarginLayoutParams) knVar).rightMargin = qnVar.G;
        ((ViewGroup.MarginLayoutParams) knVar).topMargin = qnVar.H;
        ((ViewGroup.MarginLayoutParams) knVar).bottomMargin = qnVar.I;
        knVar.A = qnVar.R;
        knVar.B = qnVar.Q;
        knVar.x = qnVar.N;
        knVar.z = qnVar.P;
        knVar.E = qnVar.w;
        knVar.F = qnVar.x;
        knVar.p = qnVar.z;
        knVar.q = qnVar.A;
        knVar.r = qnVar.B;
        knVar.G = qnVar.y;
        knVar.T = qnVar.C;
        knVar.U = qnVar.D;
        knVar.I = qnVar.T;
        knVar.H = qnVar.U;
        knVar.K = qnVar.W;
        knVar.J = qnVar.V;
        knVar.W = qnVar.l0;
        knVar.X = qnVar.m0;
        knVar.L = qnVar.X;
        knVar.M = qnVar.Y;
        knVar.P = qnVar.Z;
        knVar.Q = qnVar.a0;
        knVar.N = qnVar.b0;
        knVar.O = qnVar.c0;
        knVar.R = qnVar.d0;
        knVar.S = qnVar.e0;
        knVar.V = qnVar.E;
        knVar.c = qnVar.f;
        knVar.a = qnVar.d;
        knVar.b = qnVar.e;
        ((ViewGroup.MarginLayoutParams) knVar).width = qnVar.b;
        ((ViewGroup.MarginLayoutParams) knVar).height = qnVar.c;
        String str = qnVar.k0;
        if (str != null) {
            knVar.Y = str;
        }
        knVar.Z = qnVar.o0;
        knVar.setMarginStart(qnVar.K);
        knVar.setMarginEnd(qnVar.J);
        knVar.a();
    }

    public final Object clone() {
        pn pnVar = new pn();
        qn qnVar = pnVar.d;
        qnVar.getClass();
        qn qnVar2 = this.d;
        qnVar.a = qnVar2.a;
        qnVar.b = qnVar2.b;
        qnVar.c = qnVar2.c;
        qnVar.d = qnVar2.d;
        qnVar.e = qnVar2.e;
        qnVar.f = qnVar2.f;
        qnVar.g = qnVar2.g;
        qnVar.h = qnVar2.h;
        qnVar.i = qnVar2.i;
        qnVar.j = qnVar2.j;
        qnVar.k = qnVar2.k;
        qnVar.l = qnVar2.l;
        qnVar.m = qnVar2.m;
        qnVar.n = qnVar2.n;
        qnVar.o = qnVar2.o;
        qnVar.p = qnVar2.p;
        qnVar.q = qnVar2.q;
        qnVar.r = qnVar2.r;
        qnVar.s = qnVar2.s;
        qnVar.t = qnVar2.t;
        qnVar.u = qnVar2.u;
        qnVar.v = qnVar2.v;
        qnVar.w = qnVar2.w;
        qnVar.x = qnVar2.x;
        qnVar.y = qnVar2.y;
        qnVar.z = qnVar2.z;
        qnVar.A = qnVar2.A;
        qnVar.B = qnVar2.B;
        qnVar.C = qnVar2.C;
        qnVar.D = qnVar2.D;
        qnVar.E = qnVar2.E;
        qnVar.F = qnVar2.F;
        qnVar.G = qnVar2.G;
        qnVar.H = qnVar2.H;
        qnVar.I = qnVar2.I;
        qnVar.J = qnVar2.J;
        qnVar.K = qnVar2.K;
        qnVar.L = qnVar2.L;
        qnVar.M = qnVar2.M;
        qnVar.N = qnVar2.N;
        qnVar.O = qnVar2.O;
        qnVar.P = qnVar2.P;
        qnVar.Q = qnVar2.Q;
        qnVar.R = qnVar2.R;
        qnVar.S = qnVar2.S;
        qnVar.T = qnVar2.T;
        qnVar.U = qnVar2.U;
        qnVar.V = qnVar2.V;
        qnVar.W = qnVar2.W;
        qnVar.X = qnVar2.X;
        qnVar.Y = qnVar2.Y;
        qnVar.Z = qnVar2.Z;
        qnVar.a0 = qnVar2.a0;
        qnVar.b0 = qnVar2.b0;
        qnVar.c0 = qnVar2.c0;
        qnVar.d0 = qnVar2.d0;
        qnVar.e0 = qnVar2.e0;
        qnVar.f0 = qnVar2.f0;
        qnVar.g0 = qnVar2.g0;
        qnVar.h0 = qnVar2.h0;
        qnVar.k0 = qnVar2.k0;
        int[] iArr = qnVar2.i0;
        if (iArr == null || qnVar2.j0 != null) {
            qnVar.i0 = null;
        } else {
            qnVar.i0 = Arrays.copyOf(iArr, iArr.length);
        }
        qnVar.j0 = qnVar2.j0;
        qnVar.l0 = qnVar2.l0;
        qnVar.m0 = qnVar2.m0;
        qnVar.n0 = qnVar2.n0;
        qnVar.o0 = qnVar2.o0;
        rn rnVar = pnVar.c;
        rnVar.getClass();
        rn rnVar2 = this.c;
        rnVar2.getClass();
        rnVar.a = rnVar2.a;
        rnVar.c = rnVar2.c;
        rnVar.e = rnVar2.e;
        rnVar.d = rnVar2.d;
        sn snVar = this.b;
        int i = snVar.a;
        sn snVar2 = pnVar.b;
        snVar2.a = i;
        snVar2.c = snVar.c;
        snVar2.d = snVar.d;
        snVar2.b = snVar.b;
        tn tnVar = pnVar.e;
        tnVar.getClass();
        tn tnVar2 = this.e;
        tnVar2.getClass();
        tnVar.a = tnVar2.a;
        tnVar.b = tnVar2.b;
        tnVar.c = tnVar2.c;
        tnVar.d = tnVar2.d;
        tnVar.e = tnVar2.e;
        tnVar.f = tnVar2.f;
        tnVar.g = tnVar2.g;
        tnVar.h = tnVar2.h;
        tnVar.i = tnVar2.i;
        tnVar.j = tnVar2.j;
        tnVar.k = tnVar2.k;
        tnVar.l = tnVar2.l;
        tnVar.m = tnVar2.m;
        pnVar.a = this.a;
        return pnVar;
    }
}
