package defpackage;

/* JADX INFO: compiled from: r8-map-id-cf80f8abcb113d5feb50392a150ad1aafcd9a0d68b58b47d245bdd7749062c30 */
/* JADX INFO: loaded from: classes.dex */
public abstract class zl1 {
    public static final df a;
    public static final df b;
    public static final df c;
    public static final df d;
    public static final df e;
    public static final df f;
    public static final df g;
    public static final df h;
    public static final df i;
    public static final df j;
    public static final df k;
    public static final df l;
    public static final df m;
    public static final df n;
    public static final df o;
    public static final df p;
    public static final df q;
    public static final df r;
    public static final df s;
    public static final df t;

    static {
        jl1 jl1VarA = df.a();
        jl1VarA.b = 3;
        jl1VarA.c = "Google Play In-app Billing API version is less than 3";
        a = jl1VarA.b();
        jl1 jl1VarA2 = df.a();
        jl1VarA2.b = 3;
        jl1VarA2.c = "Google Play In-app Billing API version is less than 9";
        b = jl1VarA2.b();
        jl1 jl1VarA3 = df.a();
        jl1VarA3.b = 3;
        jl1VarA3.c = "Billing service unavailable on device.";
        c = jl1VarA3.b();
        jl1 jl1VarA4 = df.a();
        jl1VarA4.b = 2;
        jl1VarA4.c = "Billing service unavailable on device.";
        d = jl1VarA4.b();
        jl1 jl1VarA5 = df.a();
        jl1VarA5.b = 5;
        jl1VarA5.c = "Client is already in the process of connecting to billing service.";
        e = jl1VarA5.b();
        jl1 jl1VarA6 = df.a();
        jl1VarA6.b = 5;
        jl1VarA6.c = "The list of SKUs can't be empty.";
        jl1VarA6.b();
        jl1 jl1VarA7 = df.a();
        jl1VarA7.b = 5;
        jl1VarA7.c = "SKU type can't be empty.";
        jl1VarA7.b();
        jl1 jl1VarA8 = df.a();
        jl1VarA8.b = 5;
        jl1VarA8.c = "Product type can't be empty.";
        f = jl1VarA8.b();
        jl1 jl1VarA9 = df.a();
        jl1VarA9.b = -2;
        jl1VarA9.c = "Client does not support extra params.";
        g = jl1VarA9.b();
        jl1 jl1VarA10 = df.a();
        jl1VarA10.b = 5;
        jl1VarA10.c = "Invalid purchase token.";
        h = jl1VarA10.b();
        jl1 jl1VarA11 = df.a();
        jl1VarA11.b = 6;
        jl1VarA11.c = "An internal error occurred.";
        i = jl1VarA11.b();
        jl1 jl1VarA12 = df.a();
        jl1VarA12.b = 5;
        jl1VarA12.c = "SKU can't be null.";
        jl1VarA12.b();
        jl1 jl1VarA13 = df.a();
        jl1VarA13.b = 0;
        j = jl1VarA13.b();
        jl1 jl1VarA14 = df.a();
        jl1VarA14.b = -1;
        jl1VarA14.c = "Service connection is disconnected.";
        k = jl1VarA14.b();
        jl1 jl1VarA15 = df.a();
        jl1VarA15.b = 2;
        jl1VarA15.c = "Timeout communicating with service.";
        l = jl1VarA15.b();
        jl1 jl1VarA16 = df.a();
        jl1VarA16.b = -2;
        jl1VarA16.c = "Client does not support subscriptions.";
        m = jl1VarA16.b();
        jl1 jl1VarA17 = df.a();
        jl1VarA17.b = -2;
        jl1VarA17.c = "Client does not support subscriptions update.";
        jl1VarA17.b();
        jl1 jl1VarA18 = df.a();
        jl1VarA18.b = -2;
        jl1VarA18.c = "Client does not support get purchase history.";
        n = jl1VarA18.b();
        jl1 jl1VarA19 = df.a();
        jl1VarA19.b = -2;
        jl1VarA19.c = "Client does not support price change confirmation.";
        jl1VarA19.b();
        jl1 jl1VarA20 = df.a();
        jl1VarA20.b = -2;
        jl1VarA20.c = "Play Store version installed does not support cross selling products.";
        jl1VarA20.b();
        jl1 jl1VarA21 = df.a();
        jl1VarA21.b = -2;
        jl1VarA21.c = "Client does not support multi-item purchases.";
        o = jl1VarA21.b();
        jl1 jl1VarA22 = df.a();
        jl1VarA22.b = -2;
        jl1VarA22.c = "Client does not support offer_id_token.";
        p = jl1VarA22.b();
        jl1 jl1VarA23 = df.a();
        jl1VarA23.b = -2;
        jl1VarA23.c = "Client does not support ProductDetails.";
        q = jl1VarA23.b();
        jl1 jl1VarA24 = df.a();
        jl1VarA24.b = -2;
        jl1VarA24.c = "Client does not support in-app messages.";
        jl1VarA24.b();
        jl1 jl1VarA25 = df.a();
        jl1VarA25.b = -2;
        jl1VarA25.c = "Client does not support user choice billing.";
        jl1VarA25.b();
        jl1 jl1VarA26 = df.a();
        jl1VarA26.b = -2;
        jl1VarA26.c = "Play Store version installed does not support external offer.";
        jl1VarA26.b();
        jl1 jl1VarA27 = df.a();
        jl1VarA27.b = -2;
        jl1VarA27.c = "Play Store version installed does not support multi-item purchases with season pass in one cart.";
        jl1VarA27.b();
        jl1 jl1VarA28 = df.a();
        jl1VarA28.b = 5;
        jl1VarA28.c = "Unknown feature";
        jl1VarA28.b();
        jl1 jl1VarA29 = df.a();
        jl1VarA29.b = -2;
        jl1VarA29.c = "Play Store version installed does not support get billing config.";
        jl1VarA29.b();
        jl1 jl1VarA30 = df.a();
        jl1VarA30.b = -2;
        jl1VarA30.c = "Query product details with serialized docid is not supported.";
        jl1VarA30.b();
        jl1 jl1VarA31 = df.a();
        jl1VarA31.b = 4;
        jl1VarA31.c = "Item is unavailable for purchase.";
        r = jl1VarA31.b();
        jl1 jl1VarA32 = df.a();
        jl1VarA32.b = -2;
        jl1VarA32.c = "Query product details with developer specified account is not supported.";
        jl1VarA32.b();
        jl1 jl1VarA33 = df.a();
        jl1VarA33.b = -2;
        jl1VarA33.c = "Play Store version installed does not support alternative billing only.";
        jl1VarA33.b();
        jl1 jl1VarA34 = df.a();
        jl1VarA34.b = 5;
        jl1VarA34.c = "To use this API you must specify a PurchasesUpdateListener when initializing a BillingClient.";
        s = jl1VarA34.b();
        jl1 jl1VarA35 = df.a();
        jl1VarA35.b = 6;
        jl1VarA35.c = "An error occurred while retrieving billing override.";
        t = jl1VarA35.b();
    }

    public static df a(String str, int i2) {
        jl1 jl1VarA = df.a();
        jl1VarA.b = i2;
        jl1VarA.c = str;
        return jl1VarA.b();
    }
}
